// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/create": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Cretae a rc2 instance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Instance"
                ],
                "summary": "Create a ec2 instance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "instance name",
                        "name": "instanceName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "user name",
                        "name": "userName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "source",
                        "name": "source",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "instance image id",
                        "name": "instanceImageId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "instance type",
                        "name": "instanceType",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "instance",
                        "name": "cuSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "instance",
                        "name": "diskSize",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "if dry run",
                        "name": "dryRun",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1/ec2",
	Schemes:          []string{},
	Title:            "Manage EC2 API",
	Description:      "This API is used to manager aws ec2.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
